config/routes.rb
Rails.application.routes.draw do
  get 'accomodation/new'

  get 'accomodation/edit'

  get 'users/edit'

  get 'users/show'

  resources :activities

end

app/models/accomodation.rb
class Accomodation < ActiveRecord::Base
	belongs_to :user

end

app/models/activities_users.rb
class ActivitiesUsers < ActiveRecord::Base
end

app/models/activity.rb
class Activity < ActiveRecord::Base
	has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :accomodation
	has_many :activities
end

app/controllers/accomodation_controller.rb
class AccomodationController < ApplicationController
  def new
  end

  def edit
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:activity_name, :string, :activity_description, :string, :activity_details, :string, :activity_location, :string, :activity_time, :string, :activity_date, :string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def show
  end
end

app/helpers/accomodation_helper.rb
module AccomodationHelper
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accomodation/edit.html.erb
<h1>Accomodation#edit</h1>
<p>Find me in app/views/accomodation/edit.html.erb</p>

app/views/accomodation/new.html.erb
<h1>Accomodation#new</h1>
<p>Find me in app/views/accomodation/new.html.erb</p>

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :activity_name %><br>
    <%= f.text_field :activity_name %>
  </div>
  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :activity_description %><br>
    <%= f.text_field :activity_description %>
  </div>
  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :activity_details %><br>
    <%= f.text_field :activity_details %>
  </div>
  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :activity_location %><br>
    <%= f.text_field :activity_location %>
  </div>
  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :activity_time %><br>
    <%= f.text_field :activity_time %>
  </div>
  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :activity_date %><br>
    <%= f.text_field :activity_date %>
  </div>
  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h1>Listing activities</h1>

<table>
  <thead>
    <tr>
      <th>Activity name</th>
      <th>String</th>
      <th>Activity description</th>
      <th>String</th>
      <th>Activity details</th>
      <th>String</th>
      <th>Activity location</th>
      <th>String</th>
      <th>Activity time</th>
      <th>String</th>
      <th>Activity date</th>
      <th>String</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.activity_name %></td>
        <td><%= activity.string %></td>
        <td><%= activity.activity_description %></td>
        <td><%= activity.string %></td>
        <td><%= activity.activity_details %></td>
        <td><%= activity.string %></td>
        <td><%= activity.activity_location %></td>
        <td><%= activity.string %></td>
        <td><%= activity.activity_time %></td>
        <td><%= activity.string %></td>
        <td><%= activity.activity_date %></td>
        <td><%= activity.string %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Activity name:</strong>
  <%= @activity.activity_name %>
</p>

<p>
  <strong>String:</strong>
  <%= @activity.string %>
</p>

<p>
  <strong>Activity description:</strong>
  <%= @activity.activity_description %>
</p>

<p>
  <strong>String:</strong>
  <%= @activity.string %>
</p>

<p>
  <strong>Activity details:</strong>
  <%= @activity.activity_details %>
</p>

<p>
  <strong>String:</strong>
  <%= @activity.string %>
</p>

<p>
  <strong>Activity location:</strong>
  <%= @activity.activity_location %>
</p>

<p>
  <strong>String:</strong>
  <%= @activity.string %>
</p>

<p>
  <strong>Activity time:</strong>
  <%= @activity.activity_time %>
</p>

<p>
  <strong>String:</strong>
  <%= @activity.string %>
</p>

<p>
  <strong>Activity date:</strong>
  <%= @activity.activity_date %>
</p>

<p>
  <strong>String:</strong>
  <%= @activity.string %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinalProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>